### ISSUE TITLE
Problems with wss and certificates / ffmpeg not connecting to IVS

### ISSUE THREAD

**Issue by rberger** [aws-samples/aws-simple-streaming-webapp#1]
Initially I was not seeing the buttons `Open URL Server 1` and `Open URL Server 2`

If I changed frontend/src/components/stream.js so that `http` becomes `https`:

Line 110:
```
-  let protocol = window.location.protocol.replace('http', 'wss');
+  let protocol = window.location.protocol.replace('https', 'wss');
```

Line 296 (not sure if this one was needed):
```
-  let protocol = window.location.protocol.replace('http', 'wss'); // if tou are running in http, please change from https to http, 
+  let protocol = window.location.protocol.replace('https', 'wss'); // if tou are running in http, please change from https to http, 
```

As the `wss` was becoming `wsss` after the transformation

This was based on Master of today (commit 4bbbbce298bf68279c5e7cae12aa9556285fc2a5)

Once I did get the buttons to show up and got to a page based on the containers, On Chrome, it would still not allow access to the web socket servers. The message on that page from the browser under `Advanced` was:
> ec2-3-90-13-246.compute-1.amazonaws.com normally uses encryption to protect your information. When Google Chrome tried to connect to ec2-3-90-13-246.compute-1.amazonaws.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be ec2-3-90-13-246.compute-1.amazonaws.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.
>
> You cannot visit ec2-3-90-13-246.compute-1.amazonaws.com right now because the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

If I tried it with Safari I could tell Safari to ignore the certificate errors and then it would eventually say its streaming (The button would eventually turn to `StopStreaming!`. But it was still not working end to end. 

It looks like it was talking to the containers as  the Container logs showed ffmpeg starting up, running for a bit and then restarting over and over.

It looks like IVS never gets started though.

Don't know if I really fixed the issue with certificates, at least on Safari. It does seem to be talking to the containers. Or if I'm just not working right at all.

Just to remove the certificate issue, was wondering if it would work to put an Application Load Balancer in front of the containers and use certificate manager to create valid certificate. If so what would be the right way to wire up the Containers? Can you just load balance between them? Set session sticky? Not sure what other issues there may be with that.

**Comment by osmarbento-AWS** [comment]
Hi Robert,

Thank you for your feedback and ALB suggestion.
The ECS container uses a self signed container, so you would have first to allow / authorize the site and certificate to get access to the proxy ffmpeg servers 1 and/or 2.

In order to guide that, the last commit has a websocket cert check, and offers a button to open the url and allow the certificates.
Alternatively, you can open Chrome with the following command:

On Windows
```
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --ignore-certificate-errors
```

On Mac OS
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --ignore-certificate-errors --ignore-urlfetcher-cert-requests &> /dev/null 
```
I've just integrated the correction from http to https and you well mentioned.
Please use Chrome as it supports h264 natively.

The solution was designed to keep costs at minimum, reason why we didn't add an ALB.
But in order to better integrate that and avoid SSL/TLS issues, we are investigating alternatives to implement a seamless integration between app and proxy.
 
If you need to run the solution locally in http, please see the backend (README (https://github.com/aws-samples/aws-simple-streaming-webapp/tree/main/backend)).

Best regards,
Osmar Bento

**Comment by rberger** [comment]
Ok got it to work on Chrome using the ignore certificate command line and  the changes made to `frontend/src/components/stream.js . 

I did have to beef up the containers to more powerful  instances to get consistent quality with the webcam from my iMac.

 I presume you can close this ticket.
Thanks!

**Comment by rberger** [comment]
In terms of having a valid SSL Certificate without setting up an ALB, it looks like one could do the following:
* Setup [certbot/dns-route53](https://certbot-dns-route53.readthedocs.io/en/stable/) as a lambda as way to generate [Letsencrypt](https://letsencrypt.org) TLS certificates that could be used by the transwarp containers
  * There are several examples like [certbot-lambda](https://github.com/kingsoftgames/certbot-lambda) and [Free SSL certificates with Certbot in AWS Lambda](https://www.vittorionardone.it/en/2020/04/29/free-ssl-certificates-with-certbot-in-aws-lambda/)
  * The lambda is called  periodically to do the Cert updates
  * The above examples are storing the certs in S3 or ACM
  * It would be interesting instead to have the lambda have a shared EFS file system with the ECS/Fargate containers for sharing the certs generated by the Certbot
* The transwarp containers can also mount the same EFS filesystem as volumes that now has the Letsencrypt Certificates

And thus have valid certificates that get automatically renewed as needed.

I can try to put all that together, but it will take me a while since it would stretch my knowledge about several domains. But this would be a very cool pattern for AWS to support and solve a lot of other certificate problems for containers and servers since we can't use ACM for things like this.

**Comment by marloncampos-aws** [comment]
Hi Robert,

Thanks for the feedback. Regarding the containers sizing, we will have a look and adjust it to a bit to keep the quality of the video consistency. About the certs, we are still considering some options.

Once more, thank you very much for your feedbacks!
