### ISSUE TITLE
Self Generate Certificate Issue

### ISSUE THREAD

**Issue by marloncampos-aws** [aws-samples/aws-simple-streaming-webapp#3]
Assess solutions to solve the problem with self-signed certificates.

**Comment by LesserDavid** [comment]
Hi Marlon. I have managed to succesfully pull, deploy and publish the aws-simple-streaming-webapp project but cannot get the Self Generate Certificate buttons to work as they are expected. Both redirect me to some bogus websites instead of opening the url. Is there any way to workaround this issue or if not in which of the aws services involved are those created and managed?

**Comment by marloncampos-aws** [comment]
Hi Lesser.

Since the solution uses Self Generate Certificates, some browser my block it. In order to avoid this situation, you can open the chrome browser in separately just to access the website of the solution by using one of the commands below:


(be aware that you should first close all instances of your chrome browser before opening it by using the commands below)
On Windows

"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --ignore-certificate-errors

On Mac OS

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --ignore-certificate-errors --ignore-urlfetcher-cert-requests &> /dev/null 

Since you are inserting a command to open the browser ignoring the certification errors, it is important to not use the browser to other common activities. If you wish to use chrome for other activities, you will new to close it and reopen without using the commands above.

**Comment by LesserDavid** [comment]
Hi Marlon.

This worked like a charm. Though I'd like to point one thing out for all those who wants to try this solution out and stumble upon this problem as well. Once you run Chrome with the flag for ignoring self-signed certificates set to true, make sure you actaully click those buttons opening the urls, as, at least with Chrome, it won't happen on its own. Once again thanks for your help. Much appreciated.

**Comment by marloncampos-aws** [comment]
Awesome!!
